---
function:
  handler: src/newAccountAlert/index.handler
  events:
      - eventBridge:
          name: New-Account-Alerts
          pattern:
            source:
              - aws.organizations
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - "organizations.amazonaws.com"
              eventName:
                - CreateAccount
                - InviteAccountToOrganization
  memorySize: 256
  timeout: 30
  runtime: nodejs18.x
  description: new account creation alert - ${self:provider.stage}
  name: new-account-creation-alert-${self:provider.stage}
  layers:
    - { Ref: NewAccountAlertLayerLambdaLayer }
  environment:
    SNS_TOPIC_ARN: { Ref: "NewAccountTopic" }
  package:
    patterns:
      - "!**/*"
      - "src/newAccountAlert/**"